/**
 * Self-updating platform facts (WIP 60, Layer A of WIP_NEXI_PLAN_v2.md).
 *
 * Every few minutes Nexi asks the real backend for the rules the code enforces
 * (GET /api/assistant/facts: Seller Pass price, trial length, cancel rule, order
 * statuses...) and writes them to src/knowledge/90-project-facts.generated.md.
 * The keyword index notices the new file within a second and rebuilds in memory.
 *
 * Safety rules:
 *  - A failed fetch, a bad status code or a payload that does not look right NEVER
 *    touches the file. The last good snapshot keeps answering.
 *  - The file is written to a temporary name and renamed, so a half-written file is
 *    never visible to search. It is only rewritten when the text actually changed.
 *  - The endpoint returns platform rules only. No user, order or payment data is
 *    requested or stored here.
 */
const fs = require('fs');
const path = require('path');
const config = require('../config');

const HEADER = [
    '# Platform facts (generated)',
    '',
    '> Written automatically from NextaStore\'s own code by `src/sync/factsSync.js`. Do not edit this file: changes are overwritten at the next sync.',
    '> These values are the authority for prices, limits and status names. Other knowledge files must not repeat them.',
    ''
].join('\n');

// ---- Validation ------------------------------------------------------------
function isNum(v) { return typeof v === 'number' && Number.isFinite(v) && v >= 0; }
function isStrArr(v) { return Array.isArray(v) && v.length > 0 && v.every((x) => typeof x === 'string' && x.trim()); }

/** @returns {string|null} a problem description, or null when the payload is usable. */
function validateFacts(f) {
    if (!f || typeof f !== 'object') return 'payload is not an object';
    const s = f.subscription;
    if (!s || !isNum(s.pricePerMonth) || !isNum(s.trialDays) || typeof s.currency !== 'string') return 'subscription block is missing or malformed';
    if (!Array.isArray(s.periodOptionsMonths) || !s.periodOptionsMonths.every(isNum)) return 'subscription.periodOptionsMonths is malformed';
    if (!Array.isArray(f.badgeTiers) || !f.badgeTiers.length || !f.badgeTiers.every((t) => t && typeof t.label === 'string' && isNum(t.minMonths) && Array.isArray(t.perks))) return 'badgeTiers is missing or malformed';
    const o = f.orders;
    if (!o || !isStrArr(o.statuses) || !o.statusLabels || !o.sellerTransitions || !o.buyerCancel) return 'orders block is missing or malformed';
    const c = o.buyerCancel;
    if (!isNum(c.windowMinutes) || !isNum(c.limit) || !isNum(c.limitWindowDays) || !isStrArr(c.allowedStatuses)) return 'orders.buyerCancel is malformed';
    if (!isStrArr(o.fulfillmentMethods) || !isStrArr(f.listingTypes) || !isStrArr(f.onboardingSteps)) return 'fulfilment, listing types or onboarding steps are malformed';
    return null;
}

// ---- Rendering -------------------------------------------------------------
function ugx(n, currency) { return `${currency} ${Number(n).toLocaleString('en-US')}`; }
function list(arr) {
    if (arr.length <= 1) return arr.join('');
    return `${arr.slice(0, -1).join(', ')} and ${arr[arr.length - 1]}`;
}
function orList(arr) {
    if (arr.length <= 1) return arr.join('');
    return `${arr.slice(0, -1).join(', ')} or ${arr[arr.length - 1]}`;
}
function plural(n, word) { return `${n} ${word}${n === 1 ? '' : 's'}`; }

/**
 * Turns the validated payload into knowledge-file markdown. Each "##" section is one
 * searchable chunk, written in plain sentences that use the words people actually ask with.
 */
function renderFactsMarkdown(f) {
    const s = f.subscription;
    const cur = s.currency;
    const out = [HEADER];

    // Seller Pass
    const opts = s.periodOptionsMonths;
    const example = opts.find((m) => m > 1) || opts[0];
    out.push('## Seller Pass price, cost, fee and free trial');
    out.push(`Seller Pass costs ${ugx(s.pricePerMonth, cur)} per month of coverage. Every new store starts with a free trial of ${plural(s.trialDays, 'day')}.`);
    out.push(`Coverage is bought in blocks of ${orList(opts.map(String))} months at a time. The amount for a block is the monthly price times the number of months (for example ${example} month${example === 1 ? '' : 's'} is ${ugx(s.pricePerMonth * example, cur)}), and the amount entered on the subscription page must match exactly.`);
    out.push('');

    // Badges
    out.push('## Seller badge tiers: Verified Seller, Gold Partner, Platinum Partner');
    out.push(`A store earns a trust badge from its months of paid Seller Pass coverage: ${list(f.badgeTiers.map((t) => `${t.label} at ${t.minMonths} or more months`))}.`);
    if (f.subscription.badgeCountsContinuousCoverage) {
        out.push('The months count continuous paid coverage: payments made while the store is still covered add up toward the next tier, and if coverage lapses the count starts again from the next payment.');
    }
    out.push('The badge is applied when an admin approves the payment that takes the store to the threshold, and it shows only while the store is paid up.');
    for (const t of f.badgeTiers) out.push(`- ${t.label} (${t.minMonths}+ months): ${t.perks.join('; ')}.`);
    out.push('');

    // Orders
    const o = f.orders;
    const labelOf = (st) => (o.statusLabels && o.statusLabels[st]) || st;
    out.push('## Order statuses and what buyers see');
    out.push(`An order is always in one of these statuses: ${list(o.statuses)}. A new order starts as ${o.statuses[0]}.`);
    out.push(`Buyers see friendlier labels on the Orders page: ${list(o.statuses.map((st) => `${st} is shown as "${labelOf(st)}"`))}.`);
    out.push('');
    out.push('## How a seller moves an order along');
    const moves = Object.entries(o.sellerTransitions).filter(([, to]) => to.length);
    out.push(`Sellers move orders along from the dashboard: ${list(moves.map(([from, to]) => `${from} to ${orList(to)}`))}.`);
    const finals = Object.entries(o.sellerTransitions).filter(([, to]) => !to.length).map(([st]) => st);
    if (finals.length) out.push(`${list(finals)} orders are final and cannot be changed.`);
    if (o.sellerActionLabels) {
        const acts = Object.entries(o.sellerActionLabels).map(([st, label]) => `"${label}" (${st})`);
        out.push(`The dashboard buttons are ${list(acts)}.`);
    }
    out.push('');

    // Buyer cancel
    const c = o.buyerCancel;
    const sellerCancel = Object.entries(o.sellerTransitions).filter(([, to]) => to.includes('cancelled')).map(([st]) => st);
    out.push('## Can a buyer cancel an order? The cancellation rule');
    out.push(`A buyer can cancel an order from the Orders page only while it is ${orList(c.allowedStatuses)}, and only within ${plural(c.windowMinutes, 'minute')} of placing it. A short reason is required${c.reasonRequired ? '' : ' (optional)'}.`);
    out.push(`Each buyer can cancel at most ${plural(c.limit, 'order')} this way in any ${plural(c.limitWindowDays, 'day')}. After the ${c.windowMinutes}-minute window, or once the limit is used, the buyer should message the seller to ask for the cancellation.${sellerCancel.length ? ` A seller can cancel ${orList(sellerCancel.map((st) => `a ${st} order`))} at any time (for example when an item is out of stock).` : ''}`);
    out.push('');

    // Fulfilment and listings
    out.push('## Delivery, pickup and listing types');
    out.push(`At checkout each store's items are fulfilled by ${orList(o.fulfillmentMethods)}.${o.deliveryNeedsAddress ? ' Delivery needs a delivery address; pickup does not.' : ''}`);
    out.push(`A listing can be one of these types: ${orList(f.listingTypes)}. Physical listings use the cart and stock; service and digital listings work by shoppers sending an enquiry through Messages.`);
    out.push('');

    // Onboarding
    out.push('## Store setup steps');
    out.push(`Opening a store has ${f.onboardingSteps.length} steps, in this order: ${f.onboardingSteps.map((x, i) => `${i + 1}. ${x}`).join(', ')}.`);
    if (f.launchNeedsProduct) out.push('A store needs at least one product before it can be launched; the last step sends a store with no products to the product form first.');
    out.push('');

    return out.join('\n');
}

// ---- Sync ------------------------------------------------------------------
let lastEtag = null;
let lastOutcome = null;     // 'updated' | 'unchanged' | 'not-modified' | 'failed'
let timer = null;

function factsPath() { return config.factsFile; }

function writeAtomically(target, text) {
    const tmp = `${target}.${process.pid}.tmp`; // does not end in .md, so search never lists it
    fs.writeFileSync(tmp, text, 'utf8');
    fs.renameSync(tmp, target);
}

/**
 * One sync attempt. Never throws.
 * @param {{fetchImpl?: Function, apiBase?: string, target?: string}} [opts]  overrides for tests
 */
async function syncOnce(opts = {}) {
    const fetchImpl = opts.fetchImpl || fetch;
    const apiBase = opts.apiBase || config.nextastoreApiBase;
    const target = opts.target || factsPath();
    try {
        const headers = { Accept: 'application/json' };
        if (lastEtag && fs.existsSync(target)) headers['If-None-Match'] = lastEtag;
        const res = await fetchImpl(`${apiBase}/assistant/facts`, { headers, signal: AbortSignal.timeout(4000) });
        if (res.status === 304) return report('not-modified');
        if (!res.ok) return report('failed', `backend answered ${res.status}`);

        const body = await res.json();
        const facts = body && body.data;
        const problem = validateFacts(facts);
        if (problem) return report('failed', `unexpected facts payload: ${problem}`);

        const text = renderFactsMarkdown(facts);
        let current = null;
        try { current = fs.readFileSync(target, 'utf8'); } catch (e) { /* first run */ }
        lastEtag = (res.headers && res.headers.get && res.headers.get('etag')) || null;
        if (current === text) return report('unchanged');
        writeAtomically(target, text);
        return report('updated');
    } catch (err) {
        return report('failed', err && err.message ? err.message : String(err));
    }
}

function report(outcome, detail) {
    const changed = outcome !== lastOutcome && !(outcome === 'not-modified' && lastOutcome === 'unchanged') && !(outcome === 'unchanged' && lastOutcome === 'not-modified');
    lastOutcome = outcome;
    if (outcome === 'failed' && changed) console.warn(`[assistant] facts sync failed (${detail}). Keeping the last saved facts.`);
    if (outcome === 'updated') console.log('[assistant] platform facts updated from the backend.');
    return { outcome, detail };
}

/** Sync now, then every FACTS_SYNC_MS. Does nothing when FACTS_SYNC_MS=0. */
function start() {
    if (!config.factsSyncMs) return null;
    syncOnce();
    timer = setInterval(syncOnce, config.factsSyncMs);
    if (timer.unref) timer.unref();
    return timer;
}

function stop() { if (timer) clearInterval(timer); timer = null; }

/** For start-up output and the selftest. */
function describe() {
    const target = factsPath();
    let saved = null;
    try { saved = fs.statSync(target).mtime.toISOString(); } catch (e) { /* none yet */ }
    return { enabled: !!config.factsSyncMs, everyMs: config.factsSyncMs, file: target, savedAt: saved, lastOutcome };
}

module.exports = { syncOnce, start, stop, describe, validateFacts, renderFactsMarkdown };
